name: mankeli_core
description: A Core Package Which Contains Miscaellaneous Stuff Used Across All
  Of Mankeli Solutions Dart Projects
version: 0.0.6
homepage: https://mankeli.co
repository: https://github.com/Mankeli-Software/mankeli_core
issue_tracker: https://github.com/Mankeli-Software/mankeli_core/issues

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  logger: ^2.4.0
  meta: ^1.16.0

dev_dependencies:
  mankeli_analysis: ^1.1.2
