name: '[CD]' 

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
        
      - name: 'cmd_plus'
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{secrets.PUB_CREDENTIAL}}
          skipTests: true
          format: false
          dryRunOnly: false
          flutter: true
          force: true