name: '[CD]' 

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main
        
      - name: 'Publish'
        uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1